# AUTOGENERATED FROM hacs-strømkalkulator/custom_components/stromkalkulator/dso.py
# Kjør scripts/sync_dso_from_stromkalkulator.py for å regenerere.
# Manuell redigering vil bli overskrevet.

"""Kapasitetstrinn per DSO. Subset-kopi fra strømkalkulator."""

from __future__ import annotations

from typing import Final, TypedDict


class DSOInfo(TypedDict):
    """Kapasitetstrinn-data for et nettselskap."""
    navn: str
    prisomrade: str
    kapasitetstrinn: list[tuple[float, int]]  # (kW-terskel, kr/mnd)


KAPASITETSTRINN_PER_DSO: Final[dict[str, DSOInfo]] = {
    "alut": {
        "navn": "Alut",
        "prisomrade": "NO4",
        "kapasitetstrinn": [(2.0, 292), (5.0, 350), (10.0, 500), (15.0, 650), (20.0, 800), (25.0, 950), (inf, 1200)],
    },
    "area_nett": {
        "navn": "Area Nett",
        "prisomrade": "NO4",
        "kapasitetstrinn": [(2.0, 250), (5.0, 350), (10.0, 500), (15.0, 650), (20.0, 800), (25.0, 950), (inf, 1300)],
    },
    "arva": {
        "navn": "Arva",
        "prisomrade": "NO4",
        "kapasitetstrinn": [(2.0, 85), (5.0, 201), (10.0, 398), (15.0, 595), (20.0, 792), (25.0, 989), (50.0, 1972), (75.0, 2955), (100.0, 3938), (inf, 5945)],
    },
    "asker_nett": {
        "navn": "Asker Nett",
        "prisomrade": "NO1",
        "kapasitetstrinn": [(2.0, 215), (5.0, 270), (10.0, 395), (15.0, 825), (20.0, 1030), (25.0, 1300), (50.0, 1840), (75.0, 2900), (100.0, 3890), (inf, 6250)],
    },
    "barents_nett": {
        "navn": "Barents Nett",
        "prisomrade": "NO4",
        "kapasitetstrinn": [(2.0, 517), (5.0, 569), (10.0, 620), (15.0, 673), (20.0, 776), (999.0, 931)],
    },
    "bindal_kraftnett": {
        "navn": "Bindal Kraftnett",
        "prisomrade": "NO3",
        "kapasitetstrinn": [(2.0, 200), (5.0, 300), (10.0, 450), (15.0, 600), (20.0, 750), (25.0, 900), (inf, 1200)],
    },
    "bkk": {
        "navn": "BKK",
        "prisomrade": "NO5",
        "kapasitetstrinn": [(2.0, 155), (5.0, 250), (10.0, 415), (15.0, 600), (20.0, 770), (25.0, 940), (50.0, 1800), (75.0, 2650), (100.0, 3500), (inf, 6900)],
    },
    "bomlo_kraftnett": {
        "navn": "Bømlo Kraftnett",
        "prisomrade": "NO5",
        "kapasitetstrinn": [(2.0, 200), (5.0, 300), (10.0, 450), (15.0, 600), (20.0, 750), (25.0, 900), (50.0, 1500), (75.0, 2200), (100.0, 3000), (inf, 4000)],
    },
    "breheim_nett": {
        "navn": "Breheim Nett",
        "prisomrade": "NO5",
        "kapasitetstrinn": [(5.0, 225), (10.0, 350), (15.0, 500), (20.0, 650), (25.0, 800), (50.0, 1500), (75.0, 2500), (100.0, 3500), (inf, 5000)],
    },
    "de_nett": {
        "navn": "De Nett",
        "prisomrade": "NO2",
        "kapasitetstrinn": [(2.0, 286), (5.0, 369), (10.0, 451), (15.0, 622), (20.0, 787), (25.0, 957), (50.0, 1452), (75.0, 2288), (100.0, 3124), (inf, 4400)],
    },
    "elinett": {
        "navn": "Elinett",
        "prisomrade": "NO3",
        "kapasitetstrinn": [(2.0, 251), (5.0, 314), (10.0, 376), (15.0, 627), (20.0, 753), (25.0, 878), (50.0, 1254), (75.0, 1379), (100.0, 1505), (inf, 1881)],
    },
    "elmea": {
        "navn": "Elmea",
        "prisomrade": "NO4",
        "kapasitetstrinn": [(2.0, 327), (5.0, 489), (10.0, 747), (15.0, 1070), (20.0, 1392), (25.0, 1715), (50.0, 2683), (75.0, 4297), (100.0, 5911), (200.0, 11558), (inf, 24468)],
    },
    "elvenett": {
        "navn": "Elvenett",
        "prisomrade": "NO1",
        "kapasitetstrinn": [(2.0, 194), (5.0, 275), (10.0, 380), (15.0, 496), (20.0, 638), (25.0, 803), (50.0, 1133), (75.0, 1511), (100.0, 1894), (inf, 2275)],
    },
    "elvia": {
        "navn": "Elvia",
        "prisomrade": "NO1",
        "kapasitetstrinn": [(2.0, 125), (5.0, 190), (10.0, 300), (15.0, 410), (20.0, 520), (25.0, 630), (50.0, 1175), (75.0, 1720), (100.0, 2270), (inf, 4570)],
    },
    "enida": {
        "navn": "Enida",
        "prisomrade": "NO2",
        "kapasitetstrinn": [(2.0, 232), (5.0, 280), (10.0, 380), (15.0, 500), (20.0, 620), (25.0, 740), (inf, 1000)],
    },
    "etna_nett": {
        "navn": "Etna Nett",
        "prisomrade": "NO1",
        "kapasitetstrinn": [(2.0, 319), (5.0, 479), (10.0, 624), (15.0, 769), (20.0, 1015), (inf, 1269)],
    },
    "everket": {
        "navn": "Everket",
        "prisomrade": "NO2",
        "kapasitetstrinn": [(5.0, 275), (10.0, 413), (15.0, 625), (20.0, 938), (25.0, 1250), (50.0, 1746), (75.0, 2620), (100.0, 3250), (inf, 3750)],
    },
    "fagne": {
        "navn": "Fagne",
        "prisomrade": "NO2",
        "kapasitetstrinn": [(5.0, 360), (10.0, 460), (15.0, 560), (20.0, 660), (25.0, 760), (50.0, 2200), (75.0, 3200), (100.0, 4200), (inf, 5200)],
    },
    "fjellnett": {
        "navn": "Fjellnett",
        "prisomrade": "NO3",
        "kapasitetstrinn": [(2.0, 208), (5.0, 300), (10.0, 450), (15.0, 600), (20.0, 750), (25.0, 900), (inf, 1200)],
    },
    "foie": {
        "navn": "Føie",
        "prisomrade": "NO1",
        "kapasitetstrinn": [(2.0, 238), (5.0, 294), (10.0, 419), (15.0, 663), (20.0, 838), (25.0, 1075), (50.0, 1438), (75.0, 2375), (inf, 3000)],
    },
    "fore": {
        "navn": "Føre",
        "prisomrade": "NO2",
        "kapasitetstrinn": [(2.0, 329), (5.0, 428), (10.0, 526), (15.0, 625), (20.0, 724), (25.0, 823), (inf, 1000)],
    },
    "glitre": {
        "navn": "Glitre Nett",
        "prisomrade": "NO1",
        "kapasitetstrinn": [(2.0, 160), (5.0, 205), (10.0, 350), (15.0, 725), (20.0, 940), (25.0, 1180), (50.0, 1825), (75.0, 2890), (100.0, 3850), (inf, 6250)],
    },
    "griug": {
        "navn": "Griug",
        "prisomrade": "NO1",
        "kapasitetstrinn": [(2.0, 250), (5.0, 380), (10.0, 570), (15.0, 730), (20.0, 920), (25.0, 1115), (50.0, 2085), (75.0, 3060), (100.0, 4110), (inf, 8150)],
    },
    "haringnett": {
        "navn": "Haringnett",
        "prisomrade": "NO5",
        "kapasitetstrinn": [(2.0, 200), (5.0, 300), (10.0, 450), (15.0, 600), (20.0, 750), (25.0, 900), (inf, 1200)],
    },
    "havnett": {
        "navn": "Havnett",
        "prisomrade": "NO5",
        "kapasitetstrinn": [(5.0, 250), (10.0, 320), (15.0, 563), (20.0, 788), (25.0, 863), (inf, 1200)],
    },
    "holand_setskog": {
        "navn": "Høland og Setskog Elverk",
        "prisomrade": "NO1",
        "kapasitetstrinn": [(2.0, 160), (5.0, 250), (10.0, 400), (15.0, 600), (20.0, 800), (25.0, 1000), (50.0, 1800), (75.0, 2600), (100.0, 3500), (inf, 5000)],
    },
    "indre_hordaland": {
        "navn": "Indre Hordaland Kraftnett",
        "prisomrade": "NO5",
        "kapasitetstrinn": [(2.0, 240), (5.0, 300), (10.0, 450), (15.0, 600), (20.0, 750), (25.0, 900), (50.0, 1800), (75.0, 2700), (100.0, 3600), (inf, 7200)],
    },
    "jaren_everk": {
        "navn": "Jæren Everk",
        "prisomrade": "NO2",
        "kapasitetstrinn": [(2.0, 200), (5.0, 300), (10.0, 450), (15.0, 600), (20.0, 800), (25.0, 1000), (inf, 1500)],
    },
    "ke_nett": {
        "navn": "KE Nett",
        "prisomrade": "NO2",
        "kapasitetstrinn": [(2.0, 200), (5.0, 300), (10.0, 450), (15.0, 600), (20.0, 800), (25.0, 1000), (inf, 1500)],
    },
    "klive": {
        "navn": "Klive",
        "prisomrade": "NO3",
        "kapasitetstrinn": [(2.0, 200), (5.0, 300), (10.0, 450), (15.0, 600), (20.0, 750), (25.0, 900), (50.0, 1500), (inf, 2000)],
    },
    "kystnett": {
        "navn": "Kystnett",
        "prisomrade": "NO4",
        "kapasitetstrinn": [(5.0, 493), (10.0, 890), (15.0, 1286), (20.0, 1682), (25.0, 2079), (50.0, 3268), (75.0, 5250), (100.0, 7231), (inf, 10204)],
    },
    "lede": {
        "navn": "Lede",
        "prisomrade": "NO2",
        "kapasitetstrinn": [(5.0, 269), (10.0, 459), (15.0, 648), (20.0, 838), (25.0, 1028), (50.0, 1596), (75.0, 2545), (100.0, 3493), (150.0, 4915), (200.0, 6810), (inf, 9655)],
    },
    "linea": {
        "navn": "Linea",
        "prisomrade": "NO4",
        "kapasitetstrinn": [(2.0, 225), (5.0, 225), (10.0, 349), (15.0, 491), (20.0, 633), (25.0, 776), (50.0, 1297), (75.0, 2008), (100.0, 2719), (150.0, 3905), (200.0, 5326), (300.0, 7693), (400.0, 10541), (500.0, 13383), (inf, 16228)],
    },
    "linja": {
        "navn": "Linja",
        "prisomrade": "NO5",
        "kapasitetstrinn": [(2.0, 275), (5.0, 343), (10.0, 411), (15.0, 686), (20.0, 824), (25.0, 960), (50.0, 1373), (75.0, 1510), (100.0, 1646), (inf, 2059)],
    },
    "lnett": {
        "navn": "Lnett",
        "prisomrade": "NO2",
        "kapasitetstrinn": [(2.0, 150), (5.0, 250), (10.0, 400), (15.0, 650), (20.0, 900), (25.0, 1150), (50.0, 2150), (75.0, 3150), (100.0, 4150), (inf, 7000)],
    },
    "lucerna": {
        "navn": "Lucerna",
        "prisomrade": "NO4",
        "kapasitetstrinn": [(2.0, 259), (5.0, 350), (10.0, 500), (15.0, 650), (20.0, 800), (25.0, 950), (inf, 1300)],
    },
    "lysna": {
        "navn": "Lysna",
        "prisomrade": "NO5",
        "kapasitetstrinn": [(2.0, 200), (5.0, 300), (10.0, 450), (15.0, 600), (20.0, 750), (25.0, 900), (inf, 1200)],
    },
    "mellom": {
        "navn": "Mellom",
        "prisomrade": "NO3",
        "kapasitetstrinn": [(2.0, 254), (5.0, 380), (10.0, 631), (15.0, 834), (20.0, 1056), (25.0, 1323), (50.0, 1666), (inf, 2226)],
    },
    "meloy_energi": {
        "navn": "Meløy Energi",
        "prisomrade": "NO4",
        "kapasitetstrinn": [(2.0, 200), (5.0, 300), (10.0, 450), (15.0, 600), (20.0, 750), (25.0, 900), (inf, 1200)],
    },
    "midtnett": {
        "navn": "Midtnett",
        "prisomrade": "NO1",
        "kapasitetstrinn": [(5.0, 275), (10.0, 413), (15.0, 625), (20.0, 938), (25.0, 1250), (50.0, 1746), (75.0, 2620), (100.0, 3250), (inf, 3750)],
    },
    "modalen_kraftlag": {
        "navn": "Modalen Kraftlag",
        "prisomrade": "NO5",
        "kapasitetstrinn": [(2.0, 78), (5.0, 125), (10.0, 208), (15.0, 300), (20.0, 385), (25.0, 470), (50.0, 900), (75.0, 2650), (100.0, 3500), (inf, 6900)],
    },
    "netera": {
        "navn": "Netera",
        "prisomrade": "NO3",
        "kapasitetstrinn": [(10.0, 167), (63.0, 333), (inf, 667)],
    },
    "nettselskapet": {
        "navn": "Nettselskapet",
        "prisomrade": "NO3",
        "kapasitetstrinn": [(2.0, 138), (5.0, 250), (10.0, 425), (15.0, 625), (20.0, 813), (25.0, 1025), (50.0, 1750), (inf, 2750)],
    },
    "noranett": {
        "navn": "Noranett",
        "prisomrade": "NO4",
        "kapasitetstrinn": [(2.0, 310), (4.0, 440), (6.0, 530), (8.0, 610), (10.0, 680), (15.0, 750), (20.0, 890), (25.0, 1200), (30.0, 1400), (35.0, 1700), (40.0, 1900), (45.0, 2100), (50.0, 2400), (75.0, 3600), (100.0, 5300), (125.0, 7100), (150.0, 8900), (175.0, 10700), (200.0, 12500), (inf, 17800)],
    },
    "noranett_andoy": {
        "navn": "Noranett Andøy",
        "prisomrade": "NO4",
        "kapasitetstrinn": [(2.0, 310), (4.0, 440), (6.0, 530), (8.0, 610), (10.0, 680), (15.0, 750), (20.0, 890), (25.0, 1200), (inf, 1500)],
    },
    "noranett_hadsel": {
        "navn": "Noranett Hadsel",
        "prisomrade": "NO4",
        "kapasitetstrinn": [(2.0, 270), (4.0, 380), (6.0, 460), (8.0, 530), (10.0, 590), (15.0, 650), (20.0, 770), (25.0, 1040), (inf, 1300)],
    },
    "nordvest_nett": {
        "navn": "Nordvest Nett",
        "prisomrade": "NO3",
        "kapasitetstrinn": [(2.0, 158), (5.0, 388), (10.0, 478), (15.0, 726), (20.0, 861), (25.0, 1004), (50.0, 1926), (75.0, 2850), (100.0, 3773), (inf, 7420)],
    },
    "norefjell_nett": {
        "navn": "Norefjell Nett",
        "prisomrade": "NO1",
        "kapasitetstrinn": [(2.0, 200), (5.0, 300), (10.0, 450), (15.0, 600), (20.0, 750), (25.0, 900), (inf, 1200)],
    },
    "norgesnett": {
        "navn": "Norgesnett (Glitre Nett)",
        "prisomrade": "NO1",
        "kapasitetstrinn": [(2.0, 118), (5.0, 196), (10.0, 323), (15.0, 575), (20.0, 763), (25.0, 947), (50.0, 1467), (75.0, 2297), (100.0, 3126), (inf, 5067)],
    },
    "r_nett": {
        "navn": "R-Nett",
        "prisomrade": "NO1",
        "kapasitetstrinn": [(2.0, 200), (5.0, 300), (10.0, 450), (15.0, 600), (20.0, 800), (25.0, 1000), (50.0, 1800), (75.0, 2600), (100.0, 3500), (inf, 5000)],
    },
    "rakkestad_energi": {
        "navn": "Rakkestad Energi",
        "prisomrade": "NO1",
        "kapasitetstrinn": [(2.0, 125), (5.0, 190), (10.0, 300), (15.0, 410), (20.0, 520), (inf, 655)],
    },
    "rk_nett": {
        "navn": "RK Nett",
        "prisomrade": "NO2",
        "kapasitetstrinn": [(2.0, 213), (5.0, 320), (10.0, 480), (15.0, 640), (20.0, 800), (25.0, 960), (inf, 1500)],
    },
    "romsdalsnett": {
        "navn": "Romsdalsnett",
        "prisomrade": "NO3",
        "kapasitetstrinn": [(2.0, 290), (5.0, 400), (10.0, 550), (15.0, 700), (20.0, 850), (25.0, 1015), (inf, 1500)],
    },
    "s_nett": {
        "navn": "S-Nett",
        "prisomrade": "NO3",
        "kapasitetstrinn": [(2.0, 200), (5.0, 300), (10.0, 450), (15.0, 600), (20.0, 750), (25.0, 900), (inf, 1200)],
    },
    "sor_aurdal_energi": {
        "navn": "Sør Aurdal Energi",
        "prisomrade": "NO1",
        "kapasitetstrinn": [(5.0, 563), (8.0, 650), (15.0, 775), (30.0, 900), (50.0, 1013), (inf, 1375)],
    },
    "stannum": {
        "navn": "Stannum",
        "prisomrade": "NO2",
        "kapasitetstrinn": [(2.0, 200), (5.0, 300), (10.0, 450), (15.0, 600), (20.0, 750), (25.0, 900), (inf, 1200)],
    },
    "stram": {
        "navn": "Stram",
        "prisomrade": "NO4",
        "kapasitetstrinn": [(2.0, 200), (5.0, 300), (10.0, 450), (15.0, 600), (20.0, 750), (25.0, 900), (inf, 1200)],
    },
    "straumen_nett": {
        "navn": "Straumen Nett",
        "prisomrade": "NO3",
        "kapasitetstrinn": [(5.0, 290), (10.0, 334), (15.0, 495), (20.0, 582), (25.0, 873), (inf, 1163)],
    },
    "straumnett": {
        "navn": "Straumnett",
        "prisomrade": "NO5",
        "kapasitetstrinn": [(2.0, 200), (5.0, 300), (10.0, 450), (15.0, 600), (20.0, 750), (25.0, 900), (inf, 1200)],
    },
    "sygnir": {
        "navn": "Sygnir",
        "prisomrade": "NO5",
        "kapasitetstrinn": [(1.0, 240), (2.0, 288), (3.0, 338), (4.0, 384), (5.0, 431), (6.0, 504), (7.0, 575), (8.0, 648), (9.0, 720), (10.0, 791), (12.0, 938), (14.0, 1081), (16.0, 1225), (18.0, 1369), (20.0, 1519), (40.0, 2713), (60.0, 3913), (inf, 5000)],
    },
    "telemark_nett": {
        "navn": "Telemark Nett",
        "prisomrade": "NO2",
        "kapasitetstrinn": [(5.0, 284), (10.0, 400), (15.0, 550), (20.0, 700), (25.0, 850), (inf, 1200)],
    },
    "tendranett": {
        "navn": "Tendranett",
        "prisomrade": "NO5",
        "kapasitetstrinn": [(2.0, 209), (5.0, 272), (10.0, 335), (15.0, 460), (20.0, 586), (25.0, 711), (50.0, 879), (75.0, 1046), (100.0, 1213), (inf, 1255)],
    },
    "tensio_tn": {
        "navn": "Tensio TN",
        "prisomrade": "NO3",
        "kapasitetstrinn": [(2.0, 134), (5.0, 270), (10.0, 488), (15.0, 739), (20.0, 991), (25.0, 1243), (50.0, 2166), (75.0, 3427), (100.0, 4687), (150.0, 6784), (200.0, 9305), (300.0, 13500), (400.0, 18540), (500.0, 23580), (inf, 28615)],
    },
    "tensio_ts": {
        "navn": "Tensio TS",
        "prisomrade": "NO3",
        "kapasitetstrinn": [(2.0, 122), (5.0, 218), (10.0, 371), (15.0, 547), (20.0, 724), (25.0, 901), (50.0, 1547), (75.0, 2429), (100.0, 3312), (150.0, 4782), (200.0, 6545), (300.0, 9483), (400.0, 13014), (500.0, 16539), (inf, 20068)],
    },
    "tinfos": {
        "navn": "Tinfos",
        "prisomrade": "NO2",
        "kapasitetstrinn": [(5.0, 329), (10.0, 516), (15.0, 704), (20.0, 891), (25.0, 1079), (50.0, 1641), (inf, 4688)],
    },
    "uvdal_kraftforsyning": {
        "navn": "Uvdal Kraftforsyning",
        "prisomrade": "NO1",
        "kapasitetstrinn": [(5.0, 347), (10.0, 521), (15.0, 764), (20.0, 1458), (25.0, 2153), (50.0, 3194), (75.0, 4930), (100.0, 7014), (inf, 9791)],
    },
    "vang_energiverk": {
        "navn": "Vang Energiverk",
        "prisomrade": "NO1",
        "kapasitetstrinn": [(2.0, 450), (5.0, 550), (10.0, 700), (15.0, 850), (20.0, 1000), (25.0, 1165), (inf, 1165)],
    },
    "vestall": {
        "navn": "Vestall",
        "prisomrade": "NO4",
        "kapasitetstrinn": [(2.0, 150), (5.0, 250), (10.0, 400), (15.0, 550), (20.0, 700), (25.0, 850), (inf, 1100)],
    },
    "vestmar_nett": {
        "navn": "Vestmar Nett",
        "prisomrade": "NO2",
        "kapasitetstrinn": [(5.0, 291), (10.0, 515), (15.0, 745), (20.0, 970), (25.0, 1195), (50.0, 1870), (75.0, 3000), (100.0, 4100), (150.0, 5800), (200.0, 8050), (inf, 11400)],
    },
    "vevig": {
        "navn": "Vevig",
        "prisomrade": "NO3",
        "kapasitetstrinn": [(2.0, 251), (5.0, 326), (10.0, 454), (15.0, 581), (20.0, 710), (25.0, 835), (30.0, 963), (inf, 963)],
    },
    "viermie": {
        "navn": "Viermie",
        "prisomrade": "NO3",
        "kapasitetstrinn": [(5.0, 355), (10.0, 515), (15.0, 721), (20.0, 1001), (25.0, 1299), (50.0, 2469), (100.0, 4528), (200.0, 8173), (inf, 12578)],
    },
    "vissi": {
        "navn": "Vissi",
        "prisomrade": "NO4",
        "kapasitetstrinn": [(5.0, 350), (10.0, 600), (15.0, 813), (20.0, 1025), (25.0, 1238), (50.0, 1938), (75.0, 2594), (100.0, 3188), (150.0, 3813), (200.0, 4313), (inf, 4938)],
    },
}
