#!/usr/bin/env python3
"""Generer effektvakt/dso.py fra strømkalkulator/dso.py.

Krever at hacs-strømkalkulator er sjekket ut som søskenmappe:
    ~/dev/hacs-effektvakt/
    ~/dev/hacs-strømkalkulator/

Bruk:
    python scripts/sync_dso_from_stromkalkulator.py          # regenerer
    python scripts/sync_dso_from_stromkalkulator.py --check  # feiler hvis diff
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
EFFEKTVAKT_DSO = REPO_ROOT / "custom_components" / "effektvakt" / "dso.py"

# Lokalt ligger strømkalkulator som søskenmappe. I CI kan den ikke det, for
# actions/checkout nekter å skrive utenfor workspace, så stien overstyres der.
_STROMKALKULATOR_ROOT = Path(os.environ.get("STROMKALKULATOR_ROOT", REPO_ROOT.parent / "hacs-strømkalkulator"))
STROMKALKULATOR_DSO = _STROMKALKULATOR_ROOT / "custom_components" / "stromkalkulator" / "dso.py"


def _load_stromkalkulator_dso() -> dict:
    """Importer DSO_LIST fra strømkalkulator uten å installere repoet."""
    if not STROMKALKULATOR_DSO.exists():
        print(f"FEIL: Finner ikke {STROMKALKULATOR_DSO}", file=sys.stderr)
        print("Sjekk at hacs-strømkalkulator er klonet som søskenmappe.", file=sys.stderr)
        sys.exit(2)

    import importlib.util

    spec = importlib.util.spec_from_file_location("stromkalkulator_dso", STROMKALKULATOR_DSO)
    if spec is None or spec.loader is None:
        print("FEIL: Kunne ikke laste strømkalkulator/dso.py", file=sys.stderr)
        sys.exit(2)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.DSO_LIST


def _normalize_kapasitetstrinn(raw: list) -> list[tuple[float, int]]:
    """Normaliser kapasitetstrinn fra (kw, pris) eller {min, max, pris} til tuple."""
    if not raw:
        return []
    if isinstance(raw[0], dict):
        return [(float(entry["max"]), int(entry["pris"])) for entry in raw]
    return [(float(t[0]), int(t[1])) for t in raw]


def _format_kapasitetstrinn(trinn: list[tuple[float, int]]) -> str:
    """Render trinn-listen som Python-literal med eksplisitt float('inf') støtte."""
    import math

    parts = []
    for kw, pris in trinn:
        if math.isinf(kw):
            parts.append(f"(float('inf'), {pris})")
        else:
            parts.append(f"({kw}, {pris})")
    return "[" + ", ".join(parts) + "]"


def _generate(dso_list: dict) -> str:
    """Generer Python-kode for effektvakt/dso.py."""
    lines = [
        "# AUTOGENERATED FROM hacs-strømkalkulator/custom_components/stromkalkulator/dso.py",
        "# Kjør scripts/sync_dso_from_stromkalkulator.py for å regenerere.",
        "# Manuell redigering vil bli overskrevet.",
        "",
        '"""Kapasitetstrinn per DSO. Subset-kopi fra strømkalkulator."""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Final, TypedDict",
        "",
        "",
        "class DSOInfo(TypedDict):",
        '    """Kapasitetstrinn-data for et nettselskap."""',
        "    navn: str",
        "    prisomrade: str",
        "    kapasitetstrinn: list[tuple[float, int]]  # (kW-terskel, kr/mnd)",
        "",
        "",
        "KAPASITETSTRINN_PER_DSO: Final[dict[str, DSOInfo]] = {",
    ]

    for dso_id, dso in sorted(dso_list.items()):
        if not dso.get("supported", False) or dso_id == "custom":
            continue
        kapasitetstrinn = _normalize_kapasitetstrinn(dso.get("kapasitetstrinn", []))
        if not kapasitetstrinn:
            continue
        navn = dso["name"]
        prisomrade = dso.get("prisomrade", "")
        lines.append(f'    "{dso_id}": {{')
        lines.append(f'        "navn": "{navn}",')
        lines.append(f'        "prisomrade": "{prisomrade}",')
        lines.append(f'        "kapasitetstrinn": {_format_kapasitetstrinn(kapasitetstrinn)},')
        lines.append("    },")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _ruff_format(path: Path) -> None:
    """Kjør ruff format på filen slik at output alltid matcher ruff-format."""
    import subprocess

    result = subprocess.run(["ruff", "format", str(path)], capture_output=True)
    if result.returncode != 0:
        # ruff mangler, ignorer. Sync-sjekken bruker uansett samme logikk.
        pass


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Feil hvis output skiller seg fra committet fil")
    args = parser.parse_args()

    dso_list = _load_stromkalkulator_dso()
    generated = _generate(dso_list)

    if args.check:
        if not EFFEKTVAKT_DSO.exists():
            print(f"FEIL: {EFFEKTVAKT_DSO} eksisterer ikke. Kjør uten --check først.", file=sys.stderr)
            return 1
        # Skriv til en temp-fil, formater med ruff, og sammenlign
        import tempfile

        with tempfile.NamedTemporaryFile(mode="w", suffix=".py", delete=False) as tmp:
            tmp.write(generated)
            tmp_path = Path(tmp.name)
        _ruff_format(tmp_path)
        formatted = tmp_path.read_text()
        tmp_path.unlink()

        current = EFFEKTVAKT_DSO.read_text()
        if current.strip() != formatted.strip():
            print("FEIL: dso.py har driftet fra strømkalkulator.", file=sys.stderr)
            print("Kjør: python3 scripts/sync_dso_from_stromkalkulator.py", file=sys.stderr)
            return 1
        print("OK: dso.py er i sync.")
        return 0

    EFFEKTVAKT_DSO.write_text(generated)
    _ruff_format(EFFEKTVAKT_DSO)
    n = sum(1 for line in generated.splitlines() if line.startswith('    "') and line.endswith(": {"))
    print(f"Skrev {EFFEKTVAKT_DSO} ({n} DSO-er)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
